name: Test CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    environment: main_server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/test-repo || git clone https://github.com/ZebaroWhite-Alliance/test-repo ~/test-repo
            cd ~/test-repo
            git pull
            sudo systemctl restart test-repo.service
